-- Query 1 (The RDF that Hang used during development)

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wkt: <http://www.opengis.net/ont/geosparql#>
PREFIX spatial: <http://jena.apache.org/spatial#>

SELECT ?placeName ?wkt
{
  ?place spatial:nearby (34.0162520117169 -118.221390358855 10 'km') .
  ?place rdfs:label ?placeName .
  ?place wkt:asWKT ?wkt 
}

-- Query 2 (One sample of tripple from the RDF create from real pipline.)
PREFIX wkt: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

SELECT ?place ?wkt
{
  ?place rdf:type schema:Map .
  ?place wkt:asWKT ?wkt.
}
