PREFIX spatial: <http://jena.apache.org/spatial#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix wkt: <http://www.opengis.net/ont/geosparql#>

SELECT ?wkt
WHERE {
  <http://localhost:8080/source/3> schema:includesObject ?thing .
  ?thing wkt:asWKT ?wkt ;
}